http://localhost:5000/

### health

http://localhost:5000/health

### score - no anomaly

POST http://localhost:5000/score
Content-Type: application/x-www-form-urlencoded

temperature=25

### score - anomaly

POST http://localhost:5000/score
Content-Type: application/x-www-form-urlencoded

temperature=28

### score - anomaly passed as json

POST http://localhost:5000/score
content-type: application/json

{
    "temperature": 29
}
